server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_flowable?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

flowable:
  database-schema-update: true
  #\u5173\u95ED\u5B9A\u65F6\u4EFB\u52A1JOB
  async-executor-activate: false

logging:
  level:
    com.example: debug
    org.flowable.engine.impl.persistence.entity: trace